# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleMsg' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'SwiftyJSON'
# Pods for SimpleMsg

end
